// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/shipment.proto

package shipment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_PENDING    Status = 0
	Status_SHIPPED    Status = 1
	Status_ON_THE_WAY Status = 2
	Status_DELIVERED  Status = 3
	Status_UNKNOWN    Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "PENDING",
		1: "SHIPPED",
		2: "ON_THE_WAY",
		3: "DELIVERED",
		4: "UNKNOWN",
	}
	Status_value = map[string]int32{
		"PENDING":    0,
		"SHIPPED":    1,
		"ON_THE_WAY": 2,
		"DELIVERED":  3,
		"UNKNOWN":    4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_shipment_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_shipment_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{0}
}

type Shipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reference     int32                  `protobuf:"varint,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Origin        string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Status        Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=shipment.Status" json:"status,omitempty"`
	Cost          float64                `protobuf:"fixed64,6,opt,name=cost,proto3" json:"cost,omitempty"`
	DriverRevenue float64                `protobuf:"fixed64,7,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shipment) Reset() {
	*x = Shipment{}
	mi := &file_api_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shipment) ProtoMessage() {}

func (x *Shipment) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shipment.ProtoReflect.Descriptor instead.
func (*Shipment) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *Shipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Shipment) GetReference() int32 {
	if x != nil {
		return x.Reference
	}
	return 0
}

func (x *Shipment) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Shipment) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *Shipment) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PENDING
}

func (x *Shipment) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Shipment) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=shipment.Status" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PENDING
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CreateShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Reference     int32                  `protobuf:"varint,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Origin        string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Cost          float64                `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	DriverRevenue float64                `protobuf:"fixed64,6,opt,name=driver_revenue,json=driverRevenue,proto3" json:"driver_revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_api_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShipmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateShipmentRequest) GetReference() int32 {
	if x != nil {
		return x.Reference
	}
	return 0
}

func (x *CreateShipmentRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateShipmentRequest) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CreateShipmentRequest) GetDriverRevenue() float64 {
	if x != nil {
		return x.DriverRevenue
	}
	return 0
}

type CreateShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_api_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *CreateShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_api_shipment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{4}
}

func (x *GetShipmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentResponse) Reset() {
	*x = GetShipmentResponse{}
	mi := &file_api_shipment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentResponse) ProtoMessage() {}

func (x *GetShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentResponse) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{5}
}

func (x *GetShipmentResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type AddEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=shipment.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventRequest) Reset() {
	*x = AddEventRequest{}
	mi := &file_api_shipment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventRequest) ProtoMessage() {}

func (x *AddEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventRequest.ProtoReflect.Descriptor instead.
func (*AddEventRequest) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{6}
}

func (x *AddEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddEventRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PENDING
}

type AddEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shipment      *Shipment              `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventResponse) Reset() {
	*x = AddEventResponse{}
	mi := &file_api_shipment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventResponse) ProtoMessage() {}

func (x *AddEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventResponse.ProtoReflect.Descriptor instead.
func (*AddEventResponse) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{7}
}

func (x *AddEventResponse) GetShipment() *Shipment {
	if x != nil {
		return x.Shipment
	}
	return nil
}

type GetShipmentHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentHistoryRequest) Reset() {
	*x = GetShipmentHistoryRequest{}
	mi := &file_api_shipment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentHistoryRequest) ProtoMessage() {}

func (x *GetShipmentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{8}
}

func (x *GetShipmentHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetShipmentHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentHistoryResponse) Reset() {
	*x = GetShipmentHistoryResponse{}
	mi := &file_api_shipment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentHistoryResponse) ProtoMessage() {}

func (x *GetShipmentHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_shipment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetShipmentHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_shipment_proto_rawDescGZIP(), []int{9}
}

func (x *GetShipmentHistoryResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_api_shipment_proto protoreflect.FileDescriptor

const file_api_shipment_proto_rawDesc = "" +
	"\n" +
	"\x12api/shipment.proto\x12\bshipment\"\xd7\x01\n" +
	"\bShipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\treference\x18\x02 \x01(\x05R\treference\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12(\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.shipment.StatusR\x06status\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x01R\x04cost\x12%\n" +
	"\x0edriver_revenue\x18\a \x01(\x01R\rdriverRevenue\"O\n" +
	"\x05Event\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.shipment.StatusR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xba\x01\n" +
	"\x15CreateShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\treference\x18\x02 \x01(\x05R\treference\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12%\n" +
	"\x0edriver_revenue\x18\x06 \x01(\x01R\rdriverRevenue\"H\n" +
	"\x16CreateShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"$\n" +
	"\x12GetShipmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x13GetShipmentResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"K\n" +
	"\x0fAddEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.shipment.StatusR\x06status\"B\n" +
	"\x10AddEventResponse\x12.\n" +
	"\bshipment\x18\x01 \x01(\v2\x12.shipment.ShipmentR\bshipment\"+\n" +
	"\x19GetShipmentHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x1aGetShipmentHistoryResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.shipment.EventR\x06events*N\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\v\n" +
	"\aSHIPPED\x10\x01\x12\x0e\n" +
	"\n" +
	"ON_THE_WAY\x10\x02\x12\r\n" +
	"\tDELIVERED\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x042\xd6\x02\n" +
	"\x0fShipmentService\x12S\n" +
	"\x0eCreateShipment\x12\x1f.shipment.CreateShipmentRequest\x1a .shipment.CreateShipmentResponse\x12J\n" +
	"\vGetShipment\x12\x1c.shipment.GetShipmentRequest\x1a\x1d.shipment.GetShipmentResponse\x12A\n" +
	"\bAddEvent\x12\x19.shipment.AddEventRequest\x1a\x1a.shipment.AddEventResponse\x12_\n" +
	"\x12GetShipmentHistory\x12#.shipment.GetShipmentHistoryRequest\x1a$.shipment.GetShipmentHistoryResponseB&Z$shipmentVektor/api/shipment;shipmentb\x06proto3"

var (
	file_api_shipment_proto_rawDescOnce sync.Once
	file_api_shipment_proto_rawDescData []byte
)

func file_api_shipment_proto_rawDescGZIP() []byte {
	file_api_shipment_proto_rawDescOnce.Do(func() {
		file_api_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shipment_proto_rawDesc), len(file_api_shipment_proto_rawDesc)))
	})
	return file_api_shipment_proto_rawDescData
}

var file_api_shipment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_shipment_proto_goTypes = []any{
	(Status)(0),                        // 0: shipment.Status
	(*Shipment)(nil),                   // 1: shipment.Shipment
	(*Event)(nil),                      // 2: shipment.Event
	(*CreateShipmentRequest)(nil),      // 3: shipment.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),     // 4: shipment.CreateShipmentResponse
	(*GetShipmentRequest)(nil),         // 5: shipment.GetShipmentRequest
	(*GetShipmentResponse)(nil),        // 6: shipment.GetShipmentResponse
	(*AddEventRequest)(nil),            // 7: shipment.AddEventRequest
	(*AddEventResponse)(nil),           // 8: shipment.AddEventResponse
	(*GetShipmentHistoryRequest)(nil),  // 9: shipment.GetShipmentHistoryRequest
	(*GetShipmentHistoryResponse)(nil), // 10: shipment.GetShipmentHistoryResponse
}
var file_api_shipment_proto_depIdxs = []int32{
	0,  // 0: shipment.Shipment.status:type_name -> shipment.Status
	0,  // 1: shipment.Event.status:type_name -> shipment.Status
	1,  // 2: shipment.CreateShipmentResponse.shipment:type_name -> shipment.Shipment
	1,  // 3: shipment.GetShipmentResponse.shipment:type_name -> shipment.Shipment
	0,  // 4: shipment.AddEventRequest.status:type_name -> shipment.Status
	1,  // 5: shipment.AddEventResponse.shipment:type_name -> shipment.Shipment
	2,  // 6: shipment.GetShipmentHistoryResponse.events:type_name -> shipment.Event
	3,  // 7: shipment.ShipmentService.CreateShipment:input_type -> shipment.CreateShipmentRequest
	5,  // 8: shipment.ShipmentService.GetShipment:input_type -> shipment.GetShipmentRequest
	7,  // 9: shipment.ShipmentService.AddEvent:input_type -> shipment.AddEventRequest
	9,  // 10: shipment.ShipmentService.GetShipmentHistory:input_type -> shipment.GetShipmentHistoryRequest
	4,  // 11: shipment.ShipmentService.CreateShipment:output_type -> shipment.CreateShipmentResponse
	6,  // 12: shipment.ShipmentService.GetShipment:output_type -> shipment.GetShipmentResponse
	8,  // 13: shipment.ShipmentService.AddEvent:output_type -> shipment.AddEventResponse
	10, // 14: shipment.ShipmentService.GetShipmentHistory:output_type -> shipment.GetShipmentHistoryResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_shipment_proto_init() }
func file_api_shipment_proto_init() {
	if File_api_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shipment_proto_rawDesc), len(file_api_shipment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shipment_proto_goTypes,
		DependencyIndexes: file_api_shipment_proto_depIdxs,
		EnumInfos:         file_api_shipment_proto_enumTypes,
		MessageInfos:      file_api_shipment_proto_msgTypes,
	}.Build()
	File_api_shipment_proto = out.File
	file_api_shipment_proto_goTypes = nil
	file_api_shipment_proto_depIdxs = nil
}
